Add voxel_min_points param for voxel filter (ROS2)
SteveMacenski/spatio_temporal_voxel_layer pull request #161
Opened 2020-03-05 04:27 UTC by akiroz

See #160

2020-03-05 04:55 UTC, SteveMacenski requested changes
Same items from ROS1

2020-03-05 04:55 UTC, SteveMacenski commented on README.md
> +    voxel_min_points: 10         #default 0, minimum points per voxel for voxel filter
Please change this to `0`.

2020-03-05 04:55 UTC, SteveMacenski commented on src/measurement_buffer.cpp
> +      sor.setMinimumPointsNumberPerVoxel((unsigned int) _voxel_min_points);
please use `static_cast<unsigned int>(_voxel_min_points);`

2020-03-05 06:41 UTC, SteveMacenski approved these changes

2020-03-05 06:41 UTC, merged

2021-04-08 13:51 UTC, nickvaras commented
There's an issue with minimum points per voxel in PCL, so just wanted to confirm what I'd expect, which is that the feature added in this PR doesn't really have any effect when applied?? Unless it's been fixed in newer versions of PCL...

2021-04-08 19:15 UTC, SteveMacenski commented
I'm not sure - I haven't tested this personally, @akiroz I would have thought did since they proposed it

2021-04-09 01:36 UTC, akiroz commented
We actually ended up not using this param in the end but I believe it's been fixed in PCL upstream and planned for the coming 1.12 release.

2021-04-09 02:17 UTC, SteveMacenski commented
This appears to have potentially broken things per https://github.com/SteveMacenski/spatio_temporal_voxel_layer/issues/187 and https://github.com/SteveMacenski/spatio_temporal_voxel_layer/issues/199